// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Security: Use localStorage to persist sessions across page reloads
// This allows users to remain logged in when they refresh the page
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage, // ✅ Persist sessions across page reloads
    persistSession: true, // ✅ CRITICAL: Enable session persistence
    autoRefreshToken: true, // ✅ Auto-refresh access token before expiry
    detectSessionInUrl: true, // ✅ Detect session in URL (for OAuth redirects)
  },
});
