// This file is automatically generated by the Supabase CLI
// Do not edit this file manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      assets: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          name: string
          serial_number: string
          category: string
          status: string
          location: string
          user_id: string
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          name: string
          serial_number: string
          category: string
          status: string
          location: string
          user_id: string
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          name?: string
          serial_number?: string
          category?: string
          status?: string
          location?: string
          user_id?: string
        }
      }
      profiles: {
        Row: {
          id: string
          user_id: string
          username: string
          email: string
          status: 'pending' | 'approved' | 'rejected'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          username: string
          email: string
          status?: 'pending' | 'approved' | 'rejected'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          username?: string
          email?: string
          status?: 'pending' | 'approved' | 'rejected'
          created_at?: string
          updated_at?: string
        }
      }
      user_roles: {
        Row: {
          id: string
          user_id: string
          role: 'admin' | 'manager' | 'viewer'
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          role: 'admin' | 'manager' | 'viewer'
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          role?: 'admin' | 'manager' | 'viewer'
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_all_usernames: {
        Args: Record<PropertyKey, never>
        Returns: Array<{
          id: string
          user_id: string
          username: string
        }>
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
